version: '3'
services:
  server:
    image: node
    build: 
      context: ./server
    ports: 
      - 7000:7000
    command: npm run dev:server

  client:
    image: node
    build: 
      context: ./client
    ports: 
      - 5173:5173
    command: npm run dev  